### ISSUE TITLE
Add weights to the app

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#73]
Add functionality to the app so that the user can add weights to metrics.

**Comment by marlycormar** [comment]
## TODO

- [X] Update database so that certain tables contain the weights for each metric. Make any other changes accordingly.
- [ ] Display the weights for each metric for each package.
  - [ ] Change infoboxes by boxes: infoboxes don't allow shiny inputs or other text besides three pieces of information.
  - [ ] Use either the Assessment Criteria modal (default weights) or the newly created boxes to update the weights (weights per metric per selected package).
  - [ ] Display the weights on the final report.
